//! Configuration storage for tunnel-rs client configs

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;
use std::time::{SystemTime, UNIX_EPOCH};
use keyring::Entry;
use uuid::Uuid;

/// Get current Unix timestamp in seconds
fn current_timestamp() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
}

/// Iroh transport tuning configuration
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct TransportConfig {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub congestion_controller: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub receive_window: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub send_window: Option<u64>,
}

/// Iroh-specific client configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IrohConfig {
    pub server_node_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub request_source: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub target: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub relay_urls: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dns_server: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub socks5_proxy: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub auth_token: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub auth_token_file: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub alpn_token: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub alpn_token_file: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub transport: Option<TransportConfig>,
}

/// Full tunnel-rs client configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TunnelClientConfig {
    pub role: String,
    pub mode: String,
    pub iroh: IrohConfig,
}

impl TunnelClientConfig {
    /// Create a new config with default values
    pub fn new(server_node_id: String) -> Self {
        Self {
            role: "client".to_string(),
            mode: "iroh".to_string(),
            iroh: IrohConfig {
                server_node_id,
                request_source: None,
                target: None,
                relay_urls: vec![],
                dns_server: None,
                socks5_proxy: None,
                auth_token: None,
                auth_token_file: None,
                alpn_token: None,
                alpn_token_file: None,
                transport: None,
            },
        }
    }

    /// Convert to JSON string for piping to tunnel-rs via stdin
    pub fn to_json(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string(self)
    }

    /// Convert to a commented TOML string for use with `tunnel-rs client -c config.toml`
    pub fn to_commented_toml(&self, forwarding_name: &str, group_name: &str) -> String {
        let mut out = String::new();

        out.push_str(&format!("# tunnel-rs client config for forwarding: {}\n", forwarding_name));
        out.push_str(&format!("# Server group: {}\n", group_name));
        out.push_str("# Generated by tunnel-rs-manager — edit with care\n");
        out.push_str("#\n");
        out.push_str("# Usage: tunnel-rs client -c config.toml\n\n");

        out.push_str("role = \"client\"\n");
        out.push_str("mode = \"iroh\"\n\n");

        out.push_str("[iroh]\n");

        out.push_str("# The node ID of the tunnel server to connect to\n");
        out.push_str(&format!("server_node_id = {}\n", toml::Value::String(self.iroh.server_node_id.clone())));

        if let Some(ref v) = self.iroh.request_source {
            out.push_str("\n# Local address to listen on (e.g. tcp://127.0.0.1:8080)\n");
            out.push_str(&format!("request_source = {}\n", toml::Value::String(v.clone())));
        }

        if let Some(ref v) = self.iroh.target {
            out.push_str("\n# Remote target the server forwards to (e.g. 127.0.0.1:22)\n");
            out.push_str(&format!("target = {}\n", toml::Value::String(v.clone())));
        }

        if !self.iroh.relay_urls.is_empty() {
            out.push_str("\n# Relay server URLs for NAT traversal\n");
            let arr: Vec<toml::Value> = self.iroh.relay_urls.iter().map(|u| toml::Value::String(u.clone())).collect();
            out.push_str(&format!("relay_urls = {}\n", toml::Value::Array(arr)));
        }

        if let Some(ref v) = self.iroh.dns_server {
            out.push_str("\n# Custom DNS server\n");
            out.push_str(&format!("dns_server = {}\n", toml::Value::String(v.clone())));
        }

        if let Some(ref v) = self.iroh.socks5_proxy {
            out.push_str("\n# SOCKS5 proxy for outbound connections\n");
            out.push_str(&format!("socks5_proxy = {}\n", toml::Value::String(v.clone())));
        }

        if let Some(ref v) = self.iroh.auth_token {
            out.push_str("\n# Authentication token (secret — do not share)\n");
            out.push_str(&format!("auth_token = {}\n", toml::Value::String(v.clone())));
        }

        if let Some(ref v) = self.iroh.auth_token_file {
            out.push_str("\n# Path to file containing the auth token\n");
            out.push_str(&format!("auth_token_file = {}\n", toml::Value::String(v.clone())));
        }

        if let Some(ref v) = self.iroh.alpn_token {
            out.push_str("\n# ALPN protocol token (secret — do not share)\n");
            out.push_str(&format!("alpn_token = {}\n", toml::Value::String(v.clone())));
        }

        if let Some(ref v) = self.iroh.alpn_token_file {
            out.push_str("\n# Path to file containing the ALPN token\n");
            out.push_str(&format!("alpn_token_file = {}\n", toml::Value::String(v.clone())));
        }

        if let Some(ref transport) = self.iroh.transport {
            let has_fields = transport.congestion_controller.is_some()
                || transport.receive_window.is_some()
                || transport.send_window.is_some();
            if has_fields {
                out.push_str("\n# Transport tuning parameters\n");
                out.push_str("[iroh.transport]\n");
                if let Some(ref v) = transport.congestion_controller {
                    out.push_str(&format!("congestion_controller = {}\n", toml::Value::String(v.clone())));
                }
                if let Some(v) = transport.receive_window {
                    let i: i64 = v.try_into().unwrap_or(i64::MAX);
                    out.push_str(&format!("receive_window = {}\n", toml::Value::Integer(i)));
                }
                if let Some(v) = transport.send_window {
                    let i: i64 = v.try_into().unwrap_or(i64::MAX);
                    out.push_str(&format!("send_window = {}\n", toml::Value::Integer(i)));
                }
            }
        }

        out
    }
}

/// Server Group: Named collection of shared connection settings
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServerGroup {
    pub id: Uuid,
    pub name: String,
    pub server_node_id: String,
    /// Auth token is stored in the OS keyring, not configs.json.
    /// Stripped in save() and export(); restored via restore_secrets().
    #[serde(default)]
    pub auth_token: Option<String>,
    /// ALPN token is stored in the OS keyring, not configs.json.
    /// Stripped in save() and export(); restored via restore_secrets().
    #[serde(default)]
    pub alpn_token: Option<String>,
    #[serde(default)]
    pub relay_urls: Vec<String>,
    #[serde(default)]
    pub created_at: u64,
    #[serde(default)]
    pub updated_at: u64,
}

/// Forwarding: Individual named source/target pair within a server group
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Forwarding {
    pub id: Uuid,
    pub server_group_id: Uuid,
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub target: Option<String>,
    #[serde(default)]
    pub created_at: u64,
    #[serde(default)]
    pub updated_at: u64,
}

// ============================================================================
// Export/Import Data Structures
// ============================================================================

/// Export data format (shareable, no secrets)
/// The `config` field has the same structure as configs.json
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExportData {
    pub version: u32,
    pub exported_at: u64,
    pub config: ConfigStore,
}

/// Result of import operation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ImportResult {
    pub success: bool,
    pub groups_imported: usize,
    pub forwardings_imported: usize,
    pub groups_skipped: usize,
    pub forwardings_skipped: usize,
    pub errors: Vec<String>,
}

// ============================================================================
// Secrets Store
// ============================================================================

/// All secrets stored in a single keyring entry as JSON.
/// This avoids multiple macOS Keychain prompts (one per entry).
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
struct SecretsBlob {
    /// Key: "auth::{server_node_id}" or "alpn::{server_node_id}", Value: token
    tokens: HashMap<String, String>,
}

/// Secrets store backed by the OS keyring (macOS Keychain, Windows Credential Manager, etc.)
/// Uses a single keyring entry with a JSON blob to avoid repeated Keychain prompts.
pub struct SecretsStore {
    cache: std::sync::Mutex<Option<SecretsBlob>>,
}

const KEYRING_SERVICE: &str = "tunnel-rs-manager";
const KEYRING_ACCOUNT: &str = "secrets";

impl SecretsStore {
    pub fn new() -> Self {
        Self {
            cache: std::sync::Mutex::new(None),
        }
    }

    fn entry() -> Result<Entry, String> {
        Entry::new(KEYRING_SERVICE, KEYRING_ACCOUNT)
            .map_err(|e| format!("Failed to create keyring entry: {}", e))
    }

    /// Ensure cache is populated, returning a mutable reference to the blob.
    /// Caller must already hold the mutex guard.
    fn ensure_loaded(cache: &mut Option<SecretsBlob>) -> &mut SecretsBlob {
        if cache.is_none() {
            *cache = Some(Self::read_from_keyring());
        }
        cache.as_mut().unwrap()
    }

    fn read_from_keyring() -> SecretsBlob {
        let entry = match Self::entry() {
            Ok(e) => e,
            Err(e) => {
                tracing::warn!("Failed to create keyring entry: {}", e);
                return SecretsBlob::default();
            }
        };
        match entry.get_password() {
            Ok(json) => serde_json::from_str(&json).unwrap_or_default(),
            Err(keyring::Error::NoEntry) => SecretsBlob::default(),
            Err(e) => {
                tracing::warn!("Failed to read secrets from keyring: {}", e);
                SecretsBlob::default()
            }
        }
    }

    fn persist_blob(blob: &SecretsBlob) -> Result<(), String> {
        let json = serde_json::to_string(blob)
            .map_err(|e| format!("Failed to serialize secrets: {}", e))?;
        Self::entry()?
            .set_password(&json)
            .map_err(|e| format!("Failed to store secrets in keyring: {}", e))?;
        Ok(())
    }

    /// Mutate the blob under a single lock and persist to keyring.
    fn mutate(&self, f: impl FnOnce(&mut SecretsBlob)) -> Result<(), String> {
        let mut cache = self.cache.lock().unwrap();
        let blob = Self::ensure_loaded(&mut cache);
        f(blob);
        Self::persist_blob(blob)
    }

    pub fn set_token(&self, server_node_id: &str, auth_token: &str) -> Result<(), String> {
        self.mutate(|blob| {
            blob.tokens.insert(format!("auth::{}", server_node_id), auth_token.to_string());
        })
    }

    pub fn get_token(&self, server_node_id: &str) -> Option<String> {
        let mut cache = self.cache.lock().unwrap();
        let blob = Self::ensure_loaded(&mut cache);
        blob.tokens.get(&format!("auth::{}", server_node_id)).cloned()
    }

    pub fn remove_token(&self, server_node_id: &str) -> Result<(), String> {
        self.mutate(|blob| {
            blob.tokens.remove(&format!("auth::{}", server_node_id));
        })
    }

    pub fn set_alpn_token(&self, server_node_id: &str, alpn_token: &str) -> Result<(), String> {
        self.mutate(|blob| {
            blob.tokens.insert(format!("alpn::{}", server_node_id), alpn_token.to_string());
        })
    }

    pub fn get_alpn_token(&self, server_node_id: &str) -> Option<String> {
        let mut cache = self.cache.lock().unwrap();
        let blob = Self::ensure_loaded(&mut cache);
        blob.tokens.get(&format!("alpn::{}", server_node_id)).cloned()
    }

    pub fn remove_alpn_token(&self, server_node_id: &str) -> Result<(), String> {
        self.mutate(|blob| {
            blob.tokens.remove(&format!("alpn::{}", server_node_id));
        })
    }
}

// ============================================================================
// Helpers
// ============================================================================

/// Get the application data directory path
fn app_data_dir() -> Result<PathBuf, String> {
    let data_dir = dirs::data_dir()
        .ok_or_else(|| "Could not find data directory".to_string())?;
    Ok(data_dir.join("tunnel-rs-manager"))
}

/// App-wide settings (persisted)
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct AppSettings {
    pub binary_path: Option<String>,
}

impl AppSettings {
    /// Get the settings file path
    fn settings_path() -> Result<PathBuf, String> {
        Ok(app_data_dir()?.join("settings.json"))
    }

    /// Load settings from disk
    pub fn load() -> Result<Self, String> {
        let path = Self::settings_path()?;
        if !path.exists() {
            return Ok(Self::default());
        }
        let content = fs::read_to_string(&path)
            .map_err(|e| format!("Failed to read settings: {}", e))?;
        serde_json::from_str(&content)
            .map_err(|e| format!("Failed to parse settings: {}", e))
    }

    /// Save settings to disk
    pub fn save(&self) -> Result<(), String> {
        let path = Self::settings_path()?;
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .map_err(|e| format!("Failed to create settings directory: {}", e))?;
        }
        let content = serde_json::to_string_pretty(self)
            .map_err(|e| format!("Failed to serialize settings: {}", e))?;
        fs::write(&path, content)
            .map_err(|e| format!("Failed to write settings: {}", e))
    }
}

/// Config store managing server groups and forwardings
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct ConfigStore {
    pub server_groups: HashMap<Uuid, ServerGroup>,
    pub forwardings: HashMap<Uuid, Forwarding>,
}

impl ConfigStore {
    /// Get the config store file path
    fn store_path() -> Result<PathBuf, String> {
        Ok(app_data_dir()?.join("configs.json"))
    }

    /// Load config store from disk
    pub fn load() -> Result<Self, String> {
        let path = Self::store_path()?;
        if !path.exists() {
            return Ok(Self::default());
        }
        let content = fs::read_to_string(&path)
            .map_err(|e| format!("Failed to read config store: {}", e))?;
        serde_json::from_str(&content)
            .map_err(|e| format!("Failed to parse config store: {}", e))
    }

    /// Save config store to disk (auth_tokens are stripped; they're stored in the OS keyring)
    pub fn save(&self) -> Result<(), String> {
        let path = Self::store_path()?;
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .map_err(|e| format!("Failed to create config directory: {}", e))?;
        }
        // Create a copy with secrets cleared (they're stored in the OS keyring)
        let mut store_to_save = self.clone();
        for group in store_to_save.server_groups.values_mut() {
            group.auth_token = None;
            group.alpn_token = None;
        }
        let content = serde_json::to_string_pretty(&store_to_save)
            .map_err(|e| format!("Failed to serialize config store: {}", e))?;
        fs::write(&path, content)
            .map_err(|e| format!("Failed to write config store: {}", e))
    }

    /// Restore secrets (auth tokens and ALPN tokens) from SecretsStore after loading
    /// This populates the auth_token and alpn_token fields for each server group from the OS keyring
    pub fn restore_secrets(&mut self, secrets: &SecretsStore) {
        for group in self.server_groups.values_mut() {
            group.auth_token = secrets.get_token(&group.server_node_id);
            group.alpn_token = secrets.get_alpn_token(&group.server_node_id);
        }
    }

    // ============================================================================
    // Server Group CRUD
    // ============================================================================

    /// Get all server groups as a list
    pub fn list_server_groups(&self) -> Vec<ServerGroup> {
        let mut groups: Vec<_> = self.server_groups.values().cloned().collect();
        groups.sort_by(|a, b| a.name.cmp(&b.name));
        groups
    }

    /// Get a server group by ID
    pub fn get_server_group(&self, id: Uuid) -> Option<&ServerGroup> {
        self.server_groups.get(&id)
    }

    /// Add or update a server group
    pub fn upsert_server_group(&mut self, mut group: ServerGroup) -> Result<Uuid, String> {
        let now = current_timestamp();

        if let Some(existing) = self.server_groups.get(&group.id) {
            group.created_at = existing.created_at;
            group.updated_at = now;
        } else {
            group.created_at = now;
            group.updated_at = now;
        }

        let id = group.id;
        self.server_groups.insert(id, group);
        self.save()?;
        Ok(id)
    }

    /// Delete a server group by ID
    /// Returns error if the group has forwardings
    pub fn delete_server_group(&mut self, id: Uuid) -> Result<(), String> {
        // Check if any forwardings reference this group
        let has_forwardings = self.forwardings.values().any(|f| f.server_group_id == id);
        if has_forwardings {
            return Err("Cannot delete server group with existing forwardings. Delete all forwardings first.".to_string());
        }

        self.server_groups.remove(&id);
        self.save()
    }

    // ============================================================================
    // Forwarding CRUD
    // ============================================================================

    /// Get all forwardings as a list
    pub fn list_forwardings(&self) -> Vec<Forwarding> {
        let mut forwardings: Vec<_> = self.forwardings.values().cloned().collect();
        forwardings.sort_by(|a, b| a.name.cmp(&b.name));
        forwardings
    }

    /// Get all forwardings for a specific server group
    pub fn list_forwardings_by_group(&self, server_group_id: Uuid) -> Vec<Forwarding> {
        let mut forwardings: Vec<_> = self.forwardings.values()
            .filter(|f| f.server_group_id == server_group_id)
            .cloned()
            .collect();
        forwardings.sort_by(|a, b| a.name.cmp(&b.name));
        forwardings
    }

    /// Get a forwarding by ID
    pub fn get_forwarding(&self, id: Uuid) -> Option<&Forwarding> {
        self.forwardings.get(&id)
    }

    /// Add or update a forwarding
    pub fn upsert_forwarding(&mut self, mut forwarding: Forwarding) -> Result<Uuid, String> {
        // Verify server group exists
        if !self.server_groups.contains_key(&forwarding.server_group_id) {
            return Err("Server group not found".to_string());
        }

        let now = current_timestamp();

        if let Some(existing) = self.forwardings.get(&forwarding.id) {
            forwarding.created_at = existing.created_at;
            forwarding.updated_at = now;
        } else {
            forwarding.created_at = now;
            forwarding.updated_at = now;
        }

        let id = forwarding.id;
        self.forwardings.insert(id, forwarding);
        self.save()?;
        Ok(id)
    }

    /// Delete a forwarding by ID
    pub fn delete_forwarding(&mut self, id: Uuid) -> Result<(), String> {
        self.forwardings.remove(&id);
        self.save()
    }

    // ============================================================================
    // Config Building
    // ============================================================================

    /// Build a TunnelClientConfig from a forwarding ID
    /// Combines the server group settings with the forwarding's source/target
    pub fn build_tunnel_config(&self, forwarding_id: Uuid) -> Result<TunnelClientConfig, String> {
        let forwarding = self.get_forwarding(forwarding_id)
            .ok_or_else(|| "Forwarding not found".to_string())?;

        let group = self.get_server_group(forwarding.server_group_id)
            .ok_or_else(|| "Server group not found".to_string())?;

        let mut config = TunnelClientConfig::new(group.server_node_id.clone());
        config.iroh.request_source = forwarding.source.clone();
        config.iroh.target = forwarding.target.clone();
        config.iroh.auth_token = group.auth_token.clone();
        config.iroh.alpn_token = group.alpn_token.clone();
        config.iroh.relay_urls = group.relay_urls.clone();

        Ok(config)
    }

    // ============================================================================
    // Export/Import
    // ============================================================================

    /// Export all configs (auth_tokens are stripped; they're stored in the OS keyring)
    pub fn export(&self) -> ExportData {
        // Create a copy with secrets cleared (same as save())
        let mut config_to_export = self.clone();
        for group in config_to_export.server_groups.values_mut() {
            group.auth_token = None;
            group.alpn_token = None;
        }
        ExportData {
            version: 1,
            exported_at: current_timestamp(),
            config: config_to_export,
        }
    }

    /// Import configs from export data
    /// Auth tokens are NOT imported (they're not in the export) - users must add them manually
    pub fn import(&mut self, data: ExportData) -> ImportResult {
        let mut result = ImportResult {
            success: true,
            groups_imported: 0,
            forwardings_imported: 0,
            groups_skipped: 0,
            forwardings_skipped: 0,
            errors: vec![],
        };

        // Validate version
        if data.version != 1 {
            result.success = false;
            result.errors.push(format!("Unsupported export version: {}", data.version));
            return result;
        }

        let now = current_timestamp();

        // Import server groups (auth_token will be None since export() strips them)
        for (id, mut group) in data.config.server_groups {
            let is_update = self.server_groups.contains_key(&id);
            if is_update {
                let existing = self.server_groups.get(&id).unwrap();
                group.created_at = existing.created_at;
                group.updated_at = now;
            } else {
                group.created_at = now;
                group.updated_at = now;
            }

            self.server_groups.insert(id, group);
            result.groups_imported += 1;
        }

        // Import forwardings
        for (id, mut forwarding) in data.config.forwardings {
            // Verify server group exists
            if !self.server_groups.contains_key(&forwarding.server_group_id) {
                result.errors.push(format!(
                    "Server group '{}' not found for forwarding '{}'",
                    forwarding.server_group_id, forwarding.name
                ));
                result.forwardings_skipped += 1;
                continue;
            }

            let is_update = self.forwardings.contains_key(&id);
            if is_update {
                let existing = self.forwardings.get(&id).unwrap();
                forwarding.created_at = existing.created_at;
                forwarding.updated_at = now;
            } else {
                forwarding.created_at = now;
                forwarding.updated_at = now;
            }

            self.forwardings.insert(id, forwarding);
            result.forwardings_imported += 1;
        }

        // Save the updated config store
        if let Err(e) = self.save() {
            result.success = false;
            result.errors.push(format!("Failed to save config store: {}", e));
        }

        result
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_config_to_json() {
        let mut config = TunnelClientConfig::new("test123".to_string());
        config.iroh.request_source = Some("tcp://127.0.0.1:22".to_string());
        config.iroh.target = Some("127.0.0.1:2222".to_string());
        config.iroh.auth_token = Some("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX1234".to_string());
        config.iroh.alpn_token = Some("XXXXXXXXXX1234".to_string());

        let json = config.to_json().unwrap();
        let parsed: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed["role"], "client");
        assert_eq!(parsed["mode"], "iroh");
        assert_eq!(parsed["iroh"]["server_node_id"], "test123");
        assert_eq!(parsed["iroh"]["request_source"], "tcp://127.0.0.1:22");
        assert_eq!(parsed["iroh"]["target"], "127.0.0.1:2222");
    }

    #[test]
    fn test_build_tunnel_config() {
        let mut store = ConfigStore::default();

        // Create a server group
        let group_id = Uuid::new_v4();
        let group = ServerGroup {
            id: group_id,
            name: "Test Group".to_string(),
            server_node_id: "test_node_123".to_string(),
            auth_token: Some("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX1234".to_string()),
            alpn_token: Some("XXXXXXXXXX1234".to_string()),
            relay_urls: vec!["https://relay.example.com".to_string()],
            created_at: 0,
            updated_at: 0,
        };
        store.server_groups.insert(group_id, group);

        // Create a forwarding
        let fwd_id = Uuid::new_v4();
        let forwarding = Forwarding {
            id: fwd_id,
            server_group_id: group_id,
            name: "SSH".to_string(),
            source: Some("tcp://127.0.0.1:22".to_string()),
            target: Some("127.0.0.1:2222".to_string()),
            created_at: 0,
            updated_at: 0,
        };
        store.forwardings.insert(fwd_id, forwarding);

        // Build config
        let config = store.build_tunnel_config(fwd_id).unwrap();
        assert_eq!(config.iroh.server_node_id, "test_node_123");
        assert_eq!(config.iroh.request_source, Some("tcp://127.0.0.1:22".to_string()));
        assert_eq!(config.iroh.target, Some("127.0.0.1:2222".to_string()));
        assert_eq!(config.iroh.auth_token, Some("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX1234".to_string()));
        assert_eq!(config.iroh.alpn_token, Some("XXXXXXXXXX1234".to_string()));
        assert_eq!(config.iroh.relay_urls.len(), 1);
    }

    #[test]
    fn test_to_commented_toml_roundtrip() {
        let mut config = TunnelClientConfig::new("test_node_abc".to_string());
        config.iroh.request_source = Some("tcp://127.0.0.1:8080".to_string());
        config.iroh.target = Some("127.0.0.1:22".to_string());
        config.iroh.auth_token = Some("secret_auth".to_string());
        config.iroh.alpn_token = Some("secret_alpn".to_string());
        config.iroh.relay_urls = vec!["https://relay.example.com".to_string()];
        config.iroh.transport = Some(TransportConfig {
            congestion_controller: Some("bbr".to_string()),
            receive_window: Some(1048576),
            send_window: None,
        });

        let toml_str = config.to_commented_toml("My SSH", "Prod Servers");

        // Parse the generated TOML (comments are stripped by the parser)
        let parsed: toml::Value = toml_str.parse().expect("generated TOML must be valid");
        assert_eq!(parsed["role"].as_str().unwrap(), "client");
        assert_eq!(parsed["mode"].as_str().unwrap(), "iroh");
        assert_eq!(parsed["iroh"]["server_node_id"].as_str().unwrap(), "test_node_abc");
        assert_eq!(parsed["iroh"]["request_source"].as_str().unwrap(), "tcp://127.0.0.1:8080");
        assert_eq!(parsed["iroh"]["target"].as_str().unwrap(), "127.0.0.1:22");
        assert_eq!(parsed["iroh"]["auth_token"].as_str().unwrap(), "secret_auth");
        assert_eq!(parsed["iroh"]["alpn_token"].as_str().unwrap(), "secret_alpn");
        assert_eq!(parsed["iroh"]["relay_urls"].as_array().unwrap().len(), 1);
        assert_eq!(parsed["iroh"]["transport"]["congestion_controller"].as_str().unwrap(), "bbr");
        assert_eq!(parsed["iroh"]["transport"]["receive_window"].as_integer().unwrap(), 1048576);
        assert!(parsed["iroh"]["transport"].get("send_window").is_none());

        // Verify header comment is present
        assert!(toml_str.contains("# tunnel-rs client config for forwarding: My SSH"));
        assert!(toml_str.contains("# Server group: Prod Servers"));
    }
}
